services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: fanclub
      MYSQL_DATABASE: esportkalender
      MYSQL_USER: grmia
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:


