services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080" # Map your Spring Boot app port to the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/esportkalender
      SPRING_DATASOURCE_USERNAME: grmia
      SPRING_DATASOURCE_PASSWORD: userpassword

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: fanclub
      MYSQL_DATABASE: esportkalender
      MYSQL_USER: grmia
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
