services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3307/esportkalender
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fanclub

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: fanclub
      MYSQL_DATABASE: esportkalender
      MYSQL_USER: root
      MYSQL_PASSWORD: fanclub
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
