name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Compile and Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run OWASP Dependency Check
        uses: owasp/dependency-check-action@v3
        with:
          format: 'ALL' # Sender dataen ud i alle formater
          failOnCVSS: '7' #Fejler hvis den har en score på >=7

      - name: Compile and Test
        run: mvn clean verify
