name: Build, Compile, Test, and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-scan:
    name: Build, Test, and Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: runner-os-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            runner-os-maven-

      - name: Clean and Install Maven Dependencies
        run: mvn clean install -U

      - name: Run Dependency Check
        run: mvn dependency-check:check

      - name: Compile and Run Tests
        run: mvn clean test
